
# By default, SwiftLint uses a set of sensible default rules you can adjust:
disabled_rules: # rule identifiers turned on by default to exclude from running
  - line_length
  - trailing_whitespace
  - vertical_whitespace
  - orphaned_doc_comment

identifier_name:
  min_length: # Only apply to variables, parameters, enum cases, etc.
    warning: 2
    error: 2
    
# If true, SwiftLint will treat all warnings as errors.
strict: true
